#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) 
# using curl, it must return a page that contains the string Holberton School

apt-get -y update
apt-get install -y nginx
echo "Hello World!" | sudo tee /val/www/html/index.html
service nginx restart
