#!/usr/bin/env bash
# redirect 404 page not found to custom message
# sets up a new 404 error page that contains
# the string: Ceci n'est pas une page.

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /usr/share/nginx/html/custom_404.html
# OR
# echo "Hello World!" > index.html
# sudo mv index.html /var/www/html

echo "Error 404: Not found:" | sudo tee /usr/share/nginx/html/custom_404.html
echo "Ceci n'est pas une page" | sudo tee -a /usr/share/nginx/html/custom_404.html
echo "server {
	listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html;
        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
	
	error_page 404 /custom_404.html;
	location = /custom_404.html {
	root /usr/share/nginx/html;
	internal;
	}
}" > default

sudo mv -f default /etc/nginx/sites-enabled/default
sudo service nginx restart
