#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with
#+ a sleep 2 in between each iteration.

i=1
trap 'echo "I am invincible!!!"' SIGTERM
while [ $i ]; do
	echo "To infinity and beyond"
	sleep 2
done
