#!/usr/bin/env bash
# Get the process ID of the Gunicorn master process
# Send a HUP signal to the Gunicorn master process to initiate a graceful reload

kill -SIGHUP 87885
sleep 5
if ! kill -0 87885 2>/dev/null; then
	echo "Reloading Gunicorn failed. Check the logs for more information."
else
	echo "Gunicorn reloaded successfully."
fi
